/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Text;
export const AcceptRematchResult = IDL.Variant({
  'ok' : IDL.Record({ 'newGameId' : GameId }),
  'err' : IDL.Text,
});
export const AuthResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const GameMode = IDL.Variant({ 'coop' : IDL.Null, 'versus' : IDL.Null });
export const RoomCode = IDL.Text;
export const JoinToken = IDL.Text;
export const CreatePrivateGameResult = IDL.Variant({
  'ok' : IDL.Record({
    'gameId' : GameId,
    'roomCode' : RoomCode,
    'joinToken' : JoinToken,
  }),
  'err' : IDL.Text,
});
export const CreateGameResult = IDL.Variant({
  'ok' : IDL.Record({
    'gameId' : GameId,
    'roomCode' : RoomCode,
    'joinToken' : JoinToken,
  }),
  'err' : IDL.Text,
});
export const AdminSetupInfo = IDL.Record({
  'initialPassword' : IDL.Text,
  'username' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'player' : IDL.Null });
export const PlayerStats = IDL.Record({
  'totalLosses' : IDL.Nat,
  'totalWins' : IDL.Nat,
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const PlayerInfo = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'stats' : PlayerStats,
  'isDisabled' : IDL.Bool,
});
export const GameStatus = IDL.Variant({
  'won' : IDL.Nat,
  'expired' : IDL.Null,
  'lost' : IDL.Null,
  'playing' : IDL.Null,
  'waiting' : IDL.Null,
});
export const PlayerName = IDL.Text;
export const TileState = IDL.Variant({
  'present' : IDL.Null,
  'correct' : IDL.Null,
  'absent' : IDL.Null,
});
export const ExitReason = IDL.Text;
export const Guess = IDL.Record({
  'playerNum' : IDL.Nat,
  'states' : IDL.Vec(TileState),
  'word' : IDL.Text,
  'timestamp' : Timestamp,
});
export const PlayerOutcome = IDL.Variant({
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'playing' : IDL.Null,
  'opponentWon' : IDL.Null,
});
export const GameState = IDL.Record({
  'id' : GameId,
  'playerNum' : IDL.Nat,
  'status' : GameStatus,
  'currentTurnPlayer' : IDL.Opt(PlayerName),
  'opponentGuessTileStates' : IDL.Vec(IDL.Vec(TileState)),
  'exitReason' : ExitReason,
  'mode' : GameMode,
  'isHost' : IDL.Bool,
  'answer' : IDL.Opt(IDL.Text),
  'coopGuesses' : IDL.Vec(Guess),
  'myOutcome' : PlayerOutcome,
  'currentTurn' : IDL.Nat,
  'players' : IDL.Vec(PlayerName),
  'myGuesses' : IDL.Vec(Guess),
  'opponentGuessCount' : IDL.Nat,
  'isPublic' : IDL.Bool,
  'roomCode' : RoomCode,
});
export const JoinResult = IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text });
export const GameStateWithRole = IDL.Record({
  'isHost' : IDL.Bool,
  'gameState' : GameState,
});
export const GameSummary = IDL.Record({
  'id' : GameId,
  'status' : GameStatus,
  'mode' : GameMode,
  'createdAt' : Timestamp,
  'waitingForMove' : IDL.Bool,
  'players' : IDL.Vec(PlayerName),
  'isPublic' : IDL.Bool,
  'roomCode' : RoomCode,
});
export const GameHistoryEntry = IDL.Record({
  'won' : IDL.Bool,
  'endedAt' : Timestamp,
  'exitReason' : ExitReason,
  'mode' : GameMode,
  'gameId' : GameId,
  'myGuessCount' : IDL.Nat,
  'roomCode' : RoomCode,
  'opponent' : PlayerName,
});
export const OpponentRecord = IDL.Record({
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
});
export const RematchOffer = IDL.Record({
  'newGameId' : GameId,
  'offeredBy' : PlayerName,
  'roomCode' : RoomCode,
  'joinToken' : JoinToken,
});
export const LeaveResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SessionToken = IDL.Text;
export const LoginResult = IDL.Variant({
  'ok' : SessionToken,
  'err' : IDL.Text,
});
export const RegisterResult = IDL.Variant({
  'ok' : SessionToken,
  'err' : IDL.Text,
});
export const GuessError = IDL.Variant({
  'notAWord' : IDL.Null,
  'gameError' : IDL.Text,
  'notYourTurn' : IDL.Null,
});
export const GuessResultV2 = IDL.Variant({
  'ok' : GameState,
  'err' : GuessError,
});

export const idlService = IDL.Service({
  'acceptRematch' : IDL.Func([IDL.Text, GameId], [AcceptRematchResult], []),
  'addWord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthResult], []),
  'checkAndForceTimeouts' : IDL.Func([], [], []),
  'createPrivateGame' : IDL.Func(
      [IDL.Text, GameMode],
      [CreatePrivateGameResult],
      [],
    ),
  'createPublicGame' : IDL.Func([IDL.Text, GameMode], [CreateGameResult], []),
  'disablePlayer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'enablePlayer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'getAdminSetupInfo' : IDL.Func([], [IDL.Opt(AdminSetupInfo)], ['query']),
  'getAllPlayerStats' : IDL.Func([IDL.Text], [IDL.Vec(PlayerInfo)], []),
  'getAllWords' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      ['query'],
    ),
  'getGameByJoinToken' : IDL.Func([JoinToken], [IDL.Opt(GameId)], ['query']),
  'getGameState' : IDL.Func([IDL.Text, GameId], [JoinResult], ['query']),
  'getGameStateWithRole' : IDL.Func(
      [GameId, IDL.Text],
      [IDL.Opt(GameStateWithRole)],
      ['query'],
    ),
  'getMyActiveGames' : IDL.Func([IDL.Text], [IDL.Vec(GameSummary)], ['query']),
  'getMyGameHistory' : IDL.Func(
      [PlayerName],
      [IDL.Vec(GameHistoryEntry)],
      ['query'],
    ),
  'getMyOpponentStats' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, OpponentRecord))],
      ['query'],
    ),
  'getMyStats' : IDL.Func([IDL.Text], [IDL.Opt(PlayerStats)], []),
  'getRematchOffer' : IDL.Func([GameId], [IDL.Opt(RematchOffer)], ['query']),
  'getWordCount' : IDL.Func([], [IDL.Nat], ['query']),
  'importWords' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [
        IDL.Record({
          'added' : IDL.Nat,
          'skipped' : IDL.Nat,
          'duplicates' : IDL.Nat,
          'unauthorized' : IDL.Bool,
        }),
      ],
      [],
    ),
  'joinByToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(GameId)],
      [JoinResult],
      [],
    ),
  'joinGame' : IDL.Func(
      [IDL.Text, RoomCode, IDL.Opt(JoinToken)],
      [JoinResult],
      [],
    ),
  'leaveGame' : IDL.Func([IDL.Text, GameId], [LeaveResult], []),
  'listAllPlayers' : IDL.Func([IDL.Text], [IDL.Vec(PlayerInfo)], []),
  'listPublicGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'promoteToAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'newToken' : IDL.Text,
            'role' : IDL.Text,
            'message' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'recordResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Variant({ 'win' : IDL.Null, 'draw' : IDL.Null, 'loss' : IDL.Null }),
      ],
      [AuthResult],
      [],
    ),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'removeWord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'requestRematch' : IDL.Func(
      [IDL.Text, GameId],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'newGameId' : GameId,
            'roomCode' : RoomCode,
            'joinToken' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'resetPlayerPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AuthResult],
      [],
    ),
  'submitGuess' : IDL.Func([IDL.Text, GameId, IDL.Text], [GuessResultV2], []),
  'validateGuessWord' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Text;
  const AcceptRematchResult = IDL.Variant({
    'ok' : IDL.Record({ 'newGameId' : GameId }),
    'err' : IDL.Text,
  });
  const AuthResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const GameMode = IDL.Variant({ 'coop' : IDL.Null, 'versus' : IDL.Null });
  const RoomCode = IDL.Text;
  const JoinToken = IDL.Text;
  const CreatePrivateGameResult = IDL.Variant({
    'ok' : IDL.Record({
      'gameId' : GameId,
      'roomCode' : RoomCode,
      'joinToken' : JoinToken,
    }),
    'err' : IDL.Text,
  });
  const CreateGameResult = IDL.Variant({
    'ok' : IDL.Record({
      'gameId' : GameId,
      'roomCode' : RoomCode,
      'joinToken' : JoinToken,
    }),
    'err' : IDL.Text,
  });
  const AdminSetupInfo = IDL.Record({
    'initialPassword' : IDL.Text,
    'username' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'player' : IDL.Null });
  const PlayerStats = IDL.Record({
    'totalLosses' : IDL.Nat,
    'totalWins' : IDL.Nat,
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const PlayerInfo = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'stats' : PlayerStats,
    'isDisabled' : IDL.Bool,
  });
  const GameStatus = IDL.Variant({
    'won' : IDL.Nat,
    'expired' : IDL.Null,
    'lost' : IDL.Null,
    'playing' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const PlayerName = IDL.Text;
  const TileState = IDL.Variant({
    'present' : IDL.Null,
    'correct' : IDL.Null,
    'absent' : IDL.Null,
  });
  const ExitReason = IDL.Text;
  const Guess = IDL.Record({
    'playerNum' : IDL.Nat,
    'states' : IDL.Vec(TileState),
    'word' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const PlayerOutcome = IDL.Variant({
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'playing' : IDL.Null,
    'opponentWon' : IDL.Null,
  });
  const GameState = IDL.Record({
    'id' : GameId,
    'playerNum' : IDL.Nat,
    'status' : GameStatus,
    'currentTurnPlayer' : IDL.Opt(PlayerName),
    'opponentGuessTileStates' : IDL.Vec(IDL.Vec(TileState)),
    'exitReason' : ExitReason,
    'mode' : GameMode,
    'isHost' : IDL.Bool,
    'answer' : IDL.Opt(IDL.Text),
    'coopGuesses' : IDL.Vec(Guess),
    'myOutcome' : PlayerOutcome,
    'currentTurn' : IDL.Nat,
    'players' : IDL.Vec(PlayerName),
    'myGuesses' : IDL.Vec(Guess),
    'opponentGuessCount' : IDL.Nat,
    'isPublic' : IDL.Bool,
    'roomCode' : RoomCode,
  });
  const JoinResult = IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text });
  const GameStateWithRole = IDL.Record({
    'isHost' : IDL.Bool,
    'gameState' : GameState,
  });
  const GameSummary = IDL.Record({
    'id' : GameId,
    'status' : GameStatus,
    'mode' : GameMode,
    'createdAt' : Timestamp,
    'waitingForMove' : IDL.Bool,
    'players' : IDL.Vec(PlayerName),
    'isPublic' : IDL.Bool,
    'roomCode' : RoomCode,
  });
  const GameHistoryEntry = IDL.Record({
    'won' : IDL.Bool,
    'endedAt' : Timestamp,
    'exitReason' : ExitReason,
    'mode' : GameMode,
    'gameId' : GameId,
    'myGuessCount' : IDL.Nat,
    'roomCode' : RoomCode,
    'opponent' : PlayerName,
  });
  const OpponentRecord = IDL.Record({ 'wins' : IDL.Nat, 'losses' : IDL.Nat });
  const RematchOffer = IDL.Record({
    'newGameId' : GameId,
    'offeredBy' : PlayerName,
    'roomCode' : RoomCode,
    'joinToken' : JoinToken,
  });
  const LeaveResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SessionToken = IDL.Text;
  const LoginResult = IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text });
  const RegisterResult = IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text });
  const GuessError = IDL.Variant({
    'notAWord' : IDL.Null,
    'gameError' : IDL.Text,
    'notYourTurn' : IDL.Null,
  });
  const GuessResultV2 = IDL.Variant({ 'ok' : GameState, 'err' : GuessError });
  
  return IDL.Service({
    'acceptRematch' : IDL.Func([IDL.Text, GameId], [AcceptRematchResult], []),
    'addWord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'checkAndForceTimeouts' : IDL.Func([], [], []),
    'createPrivateGame' : IDL.Func(
        [IDL.Text, GameMode],
        [CreatePrivateGameResult],
        [],
      ),
    'createPublicGame' : IDL.Func([IDL.Text, GameMode], [CreateGameResult], []),
    'disablePlayer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'enablePlayer' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'getAdminSetupInfo' : IDL.Func([], [IDL.Opt(AdminSetupInfo)], ['query']),
    'getAllPlayerStats' : IDL.Func([IDL.Text], [IDL.Vec(PlayerInfo)], []),
    'getAllWords' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        ['query'],
      ),
    'getGameByJoinToken' : IDL.Func([JoinToken], [IDL.Opt(GameId)], ['query']),
    'getGameState' : IDL.Func([IDL.Text, GameId], [JoinResult], ['query']),
    'getGameStateWithRole' : IDL.Func(
        [GameId, IDL.Text],
        [IDL.Opt(GameStateWithRole)],
        ['query'],
      ),
    'getMyActiveGames' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GameSummary)],
        ['query'],
      ),
    'getMyGameHistory' : IDL.Func(
        [PlayerName],
        [IDL.Vec(GameHistoryEntry)],
        ['query'],
      ),
    'getMyOpponentStats' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, OpponentRecord))],
        ['query'],
      ),
    'getMyStats' : IDL.Func([IDL.Text], [IDL.Opt(PlayerStats)], []),
    'getRematchOffer' : IDL.Func([GameId], [IDL.Opt(RematchOffer)], ['query']),
    'getWordCount' : IDL.Func([], [IDL.Nat], ['query']),
    'importWords' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [
          IDL.Record({
            'added' : IDL.Nat,
            'skipped' : IDL.Nat,
            'duplicates' : IDL.Nat,
            'unauthorized' : IDL.Bool,
          }),
        ],
        [],
      ),
    'joinByToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(GameId)],
        [JoinResult],
        [],
      ),
    'joinGame' : IDL.Func(
        [IDL.Text, RoomCode, IDL.Opt(JoinToken)],
        [JoinResult],
        [],
      ),
    'leaveGame' : IDL.Func([IDL.Text, GameId], [LeaveResult], []),
    'listAllPlayers' : IDL.Func([IDL.Text], [IDL.Vec(PlayerInfo)], []),
    'listPublicGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'promoteToAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'newToken' : IDL.Text,
              'role' : IDL.Text,
              'message' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'recordResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Variant({
            'win' : IDL.Null,
            'draw' : IDL.Null,
            'loss' : IDL.Null,
          }),
        ],
        [AuthResult],
        [],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'removeWord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'requestRematch' : IDL.Func(
        [IDL.Text, GameId],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'newGameId' : GameId,
              'roomCode' : RoomCode,
              'joinToken' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'resetPlayerPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AuthResult],
        [],
      ),
    'submitGuess' : IDL.Func([IDL.Text, GameId, IDL.Text], [GuessResultV2], []),
    'validateGuessWord' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };