/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AcceptRematchResult = { 'ok' : { 'newGameId' : GameId } } |
  { 'err' : string };
export interface AdminSetupInfo {
  'initialPassword' : string,
  'username' : string,
}
export type AuthResult = { 'ok' : null } |
  { 'err' : string };
export type CreateGameResult = {
    'ok' : { 'gameId' : GameId, 'roomCode' : RoomCode, 'joinToken' : JoinToken }
  } |
  { 'err' : string };
export type CreatePrivateGameResult = {
    'ok' : { 'gameId' : GameId, 'roomCode' : RoomCode, 'joinToken' : JoinToken }
  } |
  { 'err' : string };
export type ExitReason = string;
export interface GameHistoryEntry {
  'won' : boolean,
  'endedAt' : Timestamp,
  'exitReason' : ExitReason,
  'mode' : GameMode,
  'gameId' : GameId,
  'myGuessCount' : bigint,
  'roomCode' : RoomCode,
  'opponent' : PlayerName,
}
export type GameId = string;
export type GameMode = { 'coop' : null } |
  { 'versus' : null };
export interface GameState {
  'id' : GameId,
  'playerNum' : bigint,
  'status' : GameStatus,
  'currentTurnPlayer' : [] | [PlayerName],
  'opponentGuessTileStates' : Array<Array<TileState>>,
  'exitReason' : ExitReason,
  'mode' : GameMode,
  'isHost' : boolean,
  'answer' : [] | [string],
  'coopGuesses' : Array<Guess>,
  'myOutcome' : PlayerOutcome,
  'currentTurn' : bigint,
  'players' : Array<PlayerName>,
  'myGuesses' : Array<Guess>,
  'opponentGuessCount' : bigint,
  'isPublic' : boolean,
  'roomCode' : RoomCode,
}
export interface GameStateWithRole {
  'isHost' : boolean,
  'gameState' : GameState,
}
export type GameStatus = { 'won' : bigint } |
  { 'expired' : null } |
  { 'lost' : null } |
  { 'playing' : null } |
  { 'waiting' : null };
export interface GameSummary {
  'id' : GameId,
  'status' : GameStatus,
  'mode' : GameMode,
  'createdAt' : Timestamp,
  'waitingForMove' : boolean,
  'players' : Array<PlayerName>,
  'isPublic' : boolean,
  'roomCode' : RoomCode,
}
export interface Guess {
  'playerNum' : bigint,
  'states' : Array<TileState>,
  'word' : string,
  'timestamp' : Timestamp,
}
export type GuessError = { 'notAWord' : null } |
  { 'gameError' : string } |
  { 'notYourTurn' : null };
export type GuessResultV2 = { 'ok' : GameState } |
  { 'err' : GuessError };
export type JoinResult = { 'ok' : GameState } |
  { 'err' : string };
export type JoinToken = string;
export type LeaveResult = { 'ok' : null } |
  { 'err' : string };
export type LoginResult = { 'ok' : SessionToken } |
  { 'err' : string };
export interface OpponentRecord { 'wins' : bigint, 'losses' : bigint }
export interface PlayerInfo {
  'username' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'stats' : PlayerStats,
  'isDisabled' : boolean,
}
export type PlayerName = string;
export type PlayerOutcome = { 'won' : null } |
  { 'lost' : null } |
  { 'playing' : null } |
  { 'opponentWon' : null };
export interface PlayerStats {
  'totalLosses' : bigint,
  'totalWins' : bigint,
  'bestStreak' : bigint,
  'currentStreak' : bigint,
}
export type RegisterResult = { 'ok' : SessionToken } |
  { 'err' : string };
export interface RematchOffer {
  'newGameId' : GameId,
  'offeredBy' : PlayerName,
  'roomCode' : RoomCode,
  'joinToken' : JoinToken,
}
export type Role = { 'admin' : null } |
  { 'player' : null };
export type RoomCode = string;
export type SessionToken = string;
export type TileState = { 'present' : null } |
  { 'correct' : null } |
  { 'absent' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'acceptRematch' : ActorMethod<[string, GameId], AcceptRematchResult>,
  'addWord' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'changePassword' : ActorMethod<[string, string, string], AuthResult>,
  'checkAndForceTimeouts' : ActorMethod<[], undefined>,
  'createPrivateGame' : ActorMethod<
    [string, GameMode],
    CreatePrivateGameResult
  >,
  'createPublicGame' : ActorMethod<[string, GameMode], CreateGameResult>,
  'disablePlayer' : ActorMethod<[string, string], AuthResult>,
  'enablePlayer' : ActorMethod<[string, string], AuthResult>,
  'getAdminSetupInfo' : ActorMethod<[], [] | [AdminSetupInfo]>,
  'getAllPlayerStats' : ActorMethod<[string], Array<PlayerInfo>>,
  'getAllWords' : ActorMethod<
    [string],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'getGameByJoinToken' : ActorMethod<[JoinToken], [] | [GameId]>,
  'getGameState' : ActorMethod<[string, GameId], JoinResult>,
  'getGameStateWithRole' : ActorMethod<
    [GameId, string],
    [] | [GameStateWithRole]
  >,
  'getMyActiveGames' : ActorMethod<[string], Array<GameSummary>>,
  'getMyGameHistory' : ActorMethod<[PlayerName], Array<GameHistoryEntry>>,
  'getMyOpponentStats' : ActorMethod<[string], Array<[string, OpponentRecord]>>,
  'getMyStats' : ActorMethod<[string], [] | [PlayerStats]>,
  'getRematchOffer' : ActorMethod<[GameId], [] | [RematchOffer]>,
  'getWordCount' : ActorMethod<[], bigint>,
  'importWords' : ActorMethod<
    [string, Array<string>],
    {
      'added' : bigint,
      'skipped' : bigint,
      'duplicates' : bigint,
      'unauthorized' : boolean,
    }
  >,
  'joinByToken' : ActorMethod<[string, string, [] | [GameId]], JoinResult>,
  'joinGame' : ActorMethod<[string, RoomCode, [] | [JoinToken]], JoinResult>,
  'leaveGame' : ActorMethod<[string, GameId], LeaveResult>,
  'listAllPlayers' : ActorMethod<[string], Array<PlayerInfo>>,
  'listPublicGames' : ActorMethod<[], Array<GameSummary>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], undefined>,
  'promoteToAdmin' : ActorMethod<
    [string, string],
    { 'ok' : { 'newToken' : string, 'role' : string, 'message' : string } } |
      { 'err' : string }
  >,
  'recordResult' : ActorMethod<
    [
      string,
      boolean,
      string,
      { 'win' : null } |
        { 'draw' : null } |
        { 'loss' : null },
    ],
    AuthResult
  >,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'removeWord' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'requestRematch' : ActorMethod<
    [string, GameId],
    {
        'ok' : {
          'newGameId' : GameId,
          'roomCode' : RoomCode,
          'joinToken' : string,
        }
      } |
      { 'err' : string }
  >,
  'resetPlayerPassword' : ActorMethod<[string, string, string], AuthResult>,
  'submitGuess' : ActorMethod<[string, GameId, string], GuessResultV2>,
  'validateGuessWord' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];