/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type LeaveResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type PlayerName = string;
export interface AdminSetupInfo {
    initialPassword: string;
    username: string;
}
export interface GameStateWithRole {
    isHost: boolean;
    gameState: GameState;
}
export interface GameSummary {
    id: GameId;
    status: GameStatus;
    mode: GameMode;
    createdAt: Timestamp;
    waitingForMove: boolean;
    players: Array<PlayerName>;
    isPublic: boolean;
    roomCode: RoomCode;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
};
export type GameId = string;
export type GameStatus = {
    __kind__: "won";
    won: bigint;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "lost";
    lost: null;
} | {
    __kind__: "playing";
    playing: null;
} | {
    __kind__: "waiting";
    waiting: null;
};
export type SessionToken = string;
export interface PlayerInfo {
    username: string;
    createdAt: Timestamp;
    role: Role;
    stats: PlayerStats;
    isDisabled: boolean;
}
export type JoinResult = {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: string;
};
export type AcceptRematchResult = {
    __kind__: "ok";
    ok: {
        newGameId: GameId;
    };
} | {
    __kind__: "err";
    err: string;
};
export type CreatePrivateGameResult = {
    __kind__: "ok";
    ok: {
        gameId: GameId;
        roomCode: RoomCode;
        joinToken: JoinToken;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface Guess {
    playerNum: bigint;
    states: Array<TileState>;
    word: string;
    timestamp: Timestamp;
}
export type AuthResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type GuessResultV2 = {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: GuessError;
};
export interface RematchOffer {
    newGameId: GameId;
    offeredBy: PlayerName;
    roomCode: RoomCode;
    joinToken: JoinToken;
}
export interface GameState {
    id: GameId;
    playerNum: bigint;
    status: GameStatus;
    currentTurnPlayer?: PlayerName;
    opponentGuessTileStates: Array<Array<TileState>>;
    exitReason: ExitReason;
    mode: GameMode;
    isHost: boolean;
    answer?: string;
    coopGuesses: Array<Guess>;
    myOutcome: PlayerOutcome;
    currentTurn: bigint;
    players: Array<PlayerName>;
    myGuesses: Array<Guess>;
    opponentGuessCount: bigint;
    isPublic: boolean;
    roomCode: RoomCode;
}
export type GuessError = {
    __kind__: "notAWord";
    notAWord: null;
} | {
    __kind__: "gameError";
    gameError: string;
} | {
    __kind__: "notYourTurn";
    notYourTurn: null;
};
export interface GameHistoryEntry {
    won: boolean;
    endedAt: Timestamp;
    exitReason: ExitReason;
    mode: GameMode;
    gameId: GameId;
    myGuessCount: bigint;
    roomCode: RoomCode;
    opponent: PlayerName;
}
export type JoinToken = string;
export type ExitReason = string;
export interface OpponentRecord {
    wins: bigint;
    losses: bigint;
}
export type CreateGameResult = {
    __kind__: "ok";
    ok: {
        gameId: GameId;
        roomCode: RoomCode;
        joinToken: JoinToken;
    };
} | {
    __kind__: "err";
    err: string;
};
export type RoomCode = string;
export type LoginResult = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
};
export interface PlayerStats {
    totalLosses: bigint;
    totalWins: bigint;
    bestStreak: bigint;
    currentStreak: bigint;
}
export enum GameMode {
    coop = "coop",
    versus = "versus"
}
export enum PlayerOutcome {
    won = "won",
    lost = "lost",
    playing = "playing",
    opponentWon = "opponentWon"
}
export enum Role {
    admin = "admin",
    player = "player"
}
export enum TileState {
    present = "present",
    correct = "correct",
    absent = "absent"
}
export enum Variant_win_draw_loss {
    win = "win",
    draw = "draw",
    loss = "loss"
}
export interface backendInterface {
    acceptRematch(sessionToken: string, originalGameId: GameId): Promise<AcceptRematchResult>;
    addWord(sessionToken: string, word: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changePassword(token: string, oldPassword: string, newPassword: string): Promise<AuthResult>;
    checkAndForceTimeouts(): Promise<void>;
    createPrivateGame(sessionToken: string, mode: GameMode): Promise<CreatePrivateGameResult>;
    createPublicGame(sessionToken: string, mode: GameMode): Promise<CreateGameResult>;
    disablePlayer(token: string, username: string): Promise<AuthResult>;
    enablePlayer(token: string, username: string): Promise<AuthResult>;
    getAdminSetupInfo(): Promise<AdminSetupInfo | null>;
    getAllPlayerStats(token: string): Promise<Array<PlayerInfo>>;
    getAllWords(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: Array<string>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getGameByJoinToken(joinToken: JoinToken): Promise<GameId | null>;
    getGameState(sessionToken: string, gameId: GameId): Promise<JoinResult>;
    getGameStateWithRole(gameId: GameId, sessionToken: string): Promise<GameStateWithRole | null>;
    getMyActiveGames(sessionToken: string): Promise<Array<GameSummary>>;
    getMyGameHistory(playerName: PlayerName): Promise<Array<GameHistoryEntry>>;
    getMyOpponentStats(token: string): Promise<Array<[string, OpponentRecord]>>;
    getMyStats(token: string): Promise<PlayerStats | null>;
    getRematchOffer(originalGameId: GameId): Promise<RematchOffer | null>;
    getWordCount(): Promise<bigint>;
    importWords(sessionToken: string, words: Array<string>): Promise<{
        added: bigint;
        skipped: bigint;
        duplicates: bigint;
        unauthorized: boolean;
    }>;
    joinByToken(sessionToken: string, joinToken: string, gameIdHint: GameId | null): Promise<JoinResult>;
    joinGame(sessionToken: string, roomCode: RoomCode, joinToken: JoinToken | null): Promise<JoinResult>;
    leaveGame(sessionToken: string, gameId: GameId): Promise<LeaveResult>;
    listAllPlayers(token: string): Promise<Array<PlayerInfo>>;
    listPublicGames(): Promise<Array<GameSummary>>;
    login(username: string, password: string): Promise<LoginResult>;
    logout(token: string): Promise<void>;
    promoteToAdmin(username: string, secretKey: string): Promise<{
        __kind__: "ok";
        ok: {
            newToken: string;
            role: string;
            message: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordResult(token: string, win: boolean, opponentName: string, outcome: Variant_win_draw_loss): Promise<AuthResult>;
    register(username: string, password: string): Promise<RegisterResult>;
    removeWord(sessionToken: string, word: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestRematch(sessionToken: string, gameId: GameId): Promise<{
        __kind__: "ok";
        ok: {
            newGameId: GameId;
            roomCode: RoomCode;
            joinToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetPlayerPassword(token: string, username: string, newPassword: string): Promise<AuthResult>;
    submitGuess(sessionToken: string, gameId: GameId, word: string): Promise<GuessResultV2>;
    validateGuessWord(word: string): Promise<boolean>;
}
import type { AcceptRematchResult as _AcceptRematchResult, AdminSetupInfo as _AdminSetupInfo, AuthResult as _AuthResult, CreateGameResult as _CreateGameResult, CreatePrivateGameResult as _CreatePrivateGameResult, ExitReason as _ExitReason, GameHistoryEntry as _GameHistoryEntry, GameId as _GameId, GameMode as _GameMode, GameState as _GameState, GameStateWithRole as _GameStateWithRole, GameStatus as _GameStatus, GameSummary as _GameSummary, Guess as _Guess, GuessError as _GuessError, GuessResultV2 as _GuessResultV2, JoinResult as _JoinResult, JoinToken as _JoinToken, LeaveResult as _LeaveResult, LoginResult as _LoginResult, PlayerInfo as _PlayerInfo, PlayerName as _PlayerName, PlayerOutcome as _PlayerOutcome, PlayerStats as _PlayerStats, RegisterResult as _RegisterResult, RematchOffer as _RematchOffer, Role as _Role, RoomCode as _RoomCode, SessionToken as _SessionToken, TileState as _TileState, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptRematch(arg0: string, arg1: GameId): Promise<AcceptRematchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRematch(arg0, arg1);
                return from_candid_AcceptRematchResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRematch(arg0, arg1);
            return from_candid_AcceptRematchResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addWord(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addWord(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWord(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAndForceTimeouts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndForceTimeouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndForceTimeouts();
            return result;
        }
    }
    async createPrivateGame(arg0: string, arg1: GameMode): Promise<CreatePrivateGameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrivateGame(arg0, to_candid_GameMode_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CreatePrivateGameResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrivateGame(arg0, to_candid_GameMode_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CreatePrivateGameResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPublicGame(arg0: string, arg1: GameMode): Promise<CreateGameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublicGame(arg0, to_candid_GameMode_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CreateGameResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublicGame(arg0, to_candid_GameMode_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CreateGameResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async disablePlayer(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.disablePlayer(arg0, arg1);
                return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disablePlayer(arg0, arg1);
            return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async enablePlayer(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.enablePlayer(arg0, arg1);
                return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enablePlayer(arg0, arg1);
            return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminSetupInfo(): Promise<AdminSetupInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSetupInfo();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSetupInfo();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayerStats(arg0: string): Promise<Array<PlayerInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerStats(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerStats(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWords(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<string>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWords(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWords(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameByJoinToken(arg0: JoinToken): Promise<GameId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameByJoinToken(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameByJoinToken(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(arg0: string, arg1: GameId): Promise<JoinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0, arg1);
                return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0, arg1);
            return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameStateWithRole(arg0: GameId, arg1: string): Promise<GameStateWithRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameStateWithRole(arg0, arg1);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameStateWithRole(arg0, arg1);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyActiveGames(arg0: string): Promise<Array<GameSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActiveGames(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActiveGames(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGameHistory(arg0: PlayerName): Promise<Array<GameHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGameHistory(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGameHistory(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOpponentStats(arg0: string): Promise<Array<[string, OpponentRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOpponentStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOpponentStats(arg0);
            return result;
        }
    }
    async getMyStats(arg0: string): Promise<PlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRematchOffer(arg0: GameId): Promise<RematchOffer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRematchOffer(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRematchOffer(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWordCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordCount();
            return result;
        }
    }
    async importWords(arg0: string, arg1: Array<string>): Promise<{
        added: bigint;
        skipped: bigint;
        duplicates: bigint;
        unauthorized: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.importWords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importWords(arg0, arg1);
            return result;
        }
    }
    async joinByToken(arg0: string, arg1: string, arg2: GameId | null): Promise<JoinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinByToken(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
                return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinByToken(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
            return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinGame(arg0: string, arg1: RoomCode, arg2: JoinToken | null): Promise<JoinResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGame(arg0, arg1, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
                return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGame(arg0, arg1, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
            return from_candid_JoinResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveGame(arg0: string, arg1: GameId): Promise<LeaveResult> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGame(arg0, arg1);
                return from_candid_LeaveResult_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGame(arg0, arg1);
            return from_candid_LeaveResult_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllPlayers(arg0: string): Promise<Array<PlayerInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPlayers(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPlayers(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublicGames(): Promise<Array<GameSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublicGames();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublicGames();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async promoteToAdmin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            newToken: string;
            role: string;
            message: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0, arg1);
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0, arg1);
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordResult(arg0: string, arg1: boolean, arg2: string, arg3: Variant_win_draw_loss): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordResult(arg0, arg1, arg2, to_candid_variant_n55(this._uploadFile, this._downloadFile, arg3));
                return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordResult(arg0, arg1, arg2, to_candid_variant_n55(this._uploadFile, this._downloadFile, arg3));
            return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_RegisterResult_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_RegisterResult_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeWord(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWord(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWord(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestRematch(arg0: string, arg1: GameId): Promise<{
        __kind__: "ok";
        ok: {
            newGameId: GameId;
            roomCode: RoomCode;
            joinToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRematch(arg0, arg1);
                return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRematch(arg0, arg1);
            return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPlayerPassword(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPlayerPassword(arg0, arg1, arg2);
                return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPlayerPassword(arg0, arg1, arg2);
            return from_candid_AuthResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitGuess(arg0: string, arg1: GameId, arg2: string): Promise<GuessResultV2> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGuess(arg0, arg1, arg2);
                return from_candid_GuessResultV2_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGuess(arg0, arg1, arg2);
            return from_candid_GuessResultV2_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateGuessWord(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateGuessWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateGuessWord(arg0);
            return result;
        }
    }
}
function from_candid_AcceptRematchResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcceptRematchResult): AcceptRematchResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CreateGameResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateGameResult): CreateGameResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CreatePrivateGameResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatePrivateGameResult): CreatePrivateGameResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GameHistoryEntry_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameHistoryEntry): GameHistoryEntry {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_GameStateWithRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStateWithRole): GameStateWithRole {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GameSummary_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSummary): GameSummary {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_GuessError_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuessError): GuessError {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_GuessResultV2_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuessResultV2): GuessResultV2 {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Guess_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guess): Guess {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_JoinResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinResult): JoinResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveResult_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveResult): LeaveResult {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerInfo_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerInfo): PlayerInfo {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerOutcome_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerOutcome): PlayerOutcome {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TileState_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TileState): TileState {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminSetupInfo]): AdminSetupInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameId]): GameId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerName]): PlayerName | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameStateWithRole]): GameStateWithRole | null {
    return value.length === 0 ? null : from_candid_GameStateWithRole_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerStats]): PlayerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RematchOffer]): RematchOffer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    createdAt: _Timestamp;
    role: _Role;
    stats: _PlayerStats;
    isDisabled: boolean;
}): {
    username: string;
    createdAt: Timestamp;
    role: Role;
    stats: PlayerStats;
    isDisabled: boolean;
} {
    return {
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_Role_n15(_uploadFile, _downloadFile, value.role),
        stats: value.stats,
        isDisabled: value.isDisabled
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    playerNum: bigint;
    status: _GameStatus;
    currentTurnPlayer: [] | [_PlayerName];
    opponentGuessTileStates: Array<Array<_TileState>>;
    exitReason: _ExitReason;
    mode: _GameMode;
    isHost: boolean;
    answer: [] | [string];
    coopGuesses: Array<_Guess>;
    myOutcome: _PlayerOutcome;
    currentTurn: bigint;
    players: Array<_PlayerName>;
    myGuesses: Array<_Guess>;
    opponentGuessCount: bigint;
    isPublic: boolean;
    roomCode: _RoomCode;
}): {
    id: GameId;
    playerNum: bigint;
    status: GameStatus;
    currentTurnPlayer?: PlayerName;
    opponentGuessTileStates: Array<Array<TileState>>;
    exitReason: ExitReason;
    mode: GameMode;
    isHost: boolean;
    answer?: string;
    coopGuesses: Array<Guess>;
    myOutcome: PlayerOutcome;
    currentTurn: bigint;
    players: Array<PlayerName>;
    myGuesses: Array<Guess>;
    opponentGuessCount: bigint;
    isPublic: boolean;
    roomCode: RoomCode;
} {
    return {
        id: value.id,
        playerNum: value.playerNum,
        status: from_candid_GameStatus_n23(_uploadFile, _downloadFile, value.status),
        currentTurnPlayer: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.currentTurnPlayer)),
        opponentGuessTileStates: from_candid_vec_n26(_uploadFile, _downloadFile, value.opponentGuessTileStates),
        exitReason: value.exitReason,
        mode: from_candid_GameMode_n30(_uploadFile, _downloadFile, value.mode),
        isHost: value.isHost,
        answer: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.answer)),
        coopGuesses: from_candid_vec_n33(_uploadFile, _downloadFile, value.coopGuesses),
        myOutcome: from_candid_PlayerOutcome_n36(_uploadFile, _downloadFile, value.myOutcome),
        currentTurn: value.currentTurn,
        players: value.players,
        myGuesses: from_candid_vec_n33(_uploadFile, _downloadFile, value.myGuesses),
        opponentGuessCount: value.opponentGuessCount,
        isPublic: value.isPublic,
        roomCode: value.roomCode
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerNum: bigint;
    states: Array<_TileState>;
    word: string;
    timestamp: _Timestamp;
}): {
    playerNum: bigint;
    states: Array<TileState>;
    word: string;
    timestamp: Timestamp;
} {
    return {
        playerNum: value.playerNum,
        states: from_candid_vec_n27(_uploadFile, _downloadFile, value.states),
        word: value.word,
        timestamp: value.timestamp
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isHost: boolean;
    gameState: _GameState;
}): {
    isHost: boolean;
    gameState: GameState;
} {
    return {
        isHost: value.isHost,
        gameState: from_candid_GameState_n21(_uploadFile, _downloadFile, value.gameState)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    status: _GameStatus;
    mode: _GameMode;
    createdAt: _Timestamp;
    waitingForMove: boolean;
    players: Array<_PlayerName>;
    isPublic: boolean;
    roomCode: _RoomCode;
}): {
    id: GameId;
    status: GameStatus;
    mode: GameMode;
    createdAt: Timestamp;
    waitingForMove: boolean;
    players: Array<PlayerName>;
    isPublic: boolean;
    roomCode: RoomCode;
} {
    return {
        id: value.id,
        status: from_candid_GameStatus_n23(_uploadFile, _downloadFile, value.status),
        mode: from_candid_GameMode_n30(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        waitingForMove: value.waitingForMove,
        players: value.players,
        isPublic: value.isPublic,
        roomCode: value.roomCode
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: boolean;
    endedAt: _Timestamp;
    exitReason: _ExitReason;
    mode: _GameMode;
    gameId: _GameId;
    myGuessCount: bigint;
    roomCode: _RoomCode;
    opponent: _PlayerName;
}): {
    won: boolean;
    endedAt: Timestamp;
    exitReason: ExitReason;
    mode: GameMode;
    gameId: GameId;
    myGuessCount: bigint;
    roomCode: RoomCode;
    opponent: PlayerName;
} {
    return {
        won: value.won,
        endedAt: value.endedAt,
        exitReason: value.exitReason,
        mode: from_candid_GameMode_n30(_uploadFile, _downloadFile, value.mode),
        gameId: value.gameId,
        myGuessCount: value.myGuessCount,
        roomCode: value.roomCode,
        opponent: value.opponent
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    player: null;
}): Role {
    return "admin" in value ? Role.admin : "player" in value ? Role.player : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<string>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        newGameId: _GameId;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        newGameId: GameId;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameState;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameState_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: bigint;
} | {
    expired: null;
} | {
    lost: null;
} | {
    playing: null;
} | {
    waiting: null;
}): {
    __kind__: "won";
    won: bigint;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "lost";
    lost: null;
} | {
    __kind__: "playing";
    playing: null;
} | {
    __kind__: "waiting";
    waiting: null;
} {
    return "won" in value ? {
        __kind__: "won",
        won: value.won
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "lost" in value ? {
        __kind__: "lost",
        lost: value.lost
    } : "playing" in value ? {
        __kind__: "playing",
        playing: value.playing
    } : "waiting" in value ? {
        __kind__: "waiting",
        waiting: value.waiting
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    correct: null;
} | {
    absent: null;
}): TileState {
    return "present" in value ? TileState.present : "correct" in value ? TileState.correct : "absent" in value ? TileState.absent : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coop: null;
} | {
    versus: null;
}): GameMode {
    return "coop" in value ? GameMode.coop : "versus" in value ? GameMode.versus : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    lost: null;
} | {
    playing: null;
} | {
    opponentWon: null;
}): PlayerOutcome {
    return "won" in value ? PlayerOutcome.won : "lost" in value ? PlayerOutcome.lost : "playing" in value ? PlayerOutcome.playing : "opponentWon" in value ? PlayerOutcome.opponentWon : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        newToken: string;
        role: string;
        message: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        newToken: string;
        role: string;
        message: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        newGameId: _GameId;
        roomCode: _RoomCode;
        joinToken: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        newGameId: GameId;
        roomCode: RoomCode;
        joinToken: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameState;
} | {
    err: _GuessError;
}): {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: GuessError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameState_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_GuessError_n60(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAWord: null;
} | {
    gameError: string;
} | {
    notYourTurn: null;
}): {
    __kind__: "notAWord";
    notAWord: null;
} | {
    __kind__: "gameError";
    gameError: string;
} | {
    __kind__: "notYourTurn";
    notYourTurn: null;
} {
    return "notAWord" in value ? {
        __kind__: "notAWord",
        notAWord: value.notAWord
    } : "gameError" in value ? {
        __kind__: "gameError",
        gameError: value.gameError
    } : "notYourTurn" in value ? {
        __kind__: "notYourTurn",
        notYourTurn: value.notYourTurn
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        gameId: _GameId;
        roomCode: _RoomCode;
        joinToken: _JoinToken;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        gameId: GameId;
        roomCode: RoomCode;
        joinToken: JoinToken;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerInfo>): Array<PlayerInfo> {
    return value.map((x)=>from_candid_PlayerInfo_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_TileState>>): Array<Array<TileState>> {
    return value.map((x)=>from_candid_vec_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TileState>): Array<TileState> {
    return value.map((x)=>from_candid_TileState_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guess>): Array<Guess> {
    return value.map((x)=>from_candid_Guess_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameSummary>): Array<GameSummary> {
    return value.map((x)=>from_candid_GameSummary_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameHistoryEntry>): Array<GameHistoryEntry> {
    return value.map((x)=>from_candid_GameHistoryEntry_n45(_uploadFile, _downloadFile, x));
}
function to_candid_GameMode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameId | null): [] | [_GameId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinToken | null): [] | [_JoinToken] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_win_draw_loss): {
    win: null;
} | {
    draw: null;
} | {
    loss: null;
} {
    return value == Variant_win_draw_loss.win ? {
        win: null
    } : value == Variant_win_draw_loss.draw ? {
        draw: null
    } : value == Variant_win_draw_loss.loss ? {
        loss: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    coop: null;
} | {
    versus: null;
} {
    return value == GameMode.coop ? {
        coop: null
    } : value == GameMode.versus ? {
        versus: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
